#!/usr/bin/env node
// build — assemble the website into site/ from the desktop widget's own front end, so the renderer,
// the stylesheet and the markup stay single-sourced in widget/:
//
//   widget/renderer.js, widget/style.css, widget/icon.png   copied as-is
//   widget/index.html                                       CSP, script tag and switcher slot swapped in
//   web/wc.js, web/web.css, web/firebase-config.js          the browser stand-ins for Electron
//   site-config.js                                          the site's competitions + live API base
//
// Run by the Pages workflow and by Vercel's build. `node web/build.mjs`, then serve site/.

import { cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { COMPETITIONS, SITE_COMPETITIONS } from "../competition.mjs";

const at = (p) => new URL(`../${p}`, import.meta.url);
const OUT = at("site/");
// the Vercel live functions (/api/live/<code>); the Vercel-hosted copy of the site calls them same-origin
const LIVE_BASE = process.env.FUTBOL_LIVE_BASE || "https://futbol-lab.vercel.app/api/live";

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT);
for (const f of ["widget/renderer.js", "widget/style.css", "widget/icon.png", "web/wc.js", "web/web.css", "web/firebase-config.js"])
  cpSync(at(f), new URL(f.split("/").pop(), OUT));

const comps = SITE_COMPETITIONS.map((code) => ({ code, key: COMPETITIONS[code].key, short: COMPETITIONS[code].short, name: COMPETITIONS[code].name }));
writeFileSync(new URL("site-config.js", OUT),
  `// generated by web/build.mjs\nexport const COMPETITIONS = ${JSON.stringify(comps)};\nexport const LIVE_BASE = ${JSON.stringify(LIVE_BASE)};\n`);

// the browser needs Firebase (gstatic), Google sign-in (apis.google.com + the auth domain's frame),
// Firestore and the live API — nothing else. Still no inline script.
const CSP = [
  "default-src 'none'",
  "img-src 'self' https: data:",
  "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
  "font-src https://fonts.gstatic.com",
  "script-src 'self' https://www.gstatic.com https://apis.google.com",
  "connect-src 'self' https://firestore.googleapis.com https://identitytoolkit.googleapis.com https://securetoken.googleapis.com https://www.googleapis.com https://*.vercel.app",
  "frame-src https://champions-league-a650f.firebaseapp.com https://accounts.google.com https://apis.google.com",
  "base-uri 'none'",
  "form-action 'none'",
].join("; ");

let html = readFileSync(at("widget/index.html"), "utf8");
const swap = (from, to, what) => {
  if (!from.test(html)) throw new Error(`web/build: couldn't find ${what} in widget/index.html — update the build`);
  html = html.replace(from, to);
};
swap(/<meta http-equiv="Content-Security-Policy"[^>]*\/>/, `<meta http-equiv="Content-Security-Policy" content="${CSP}" />\n<link rel="icon" href="icon.png" />`, "the CSP meta tag");
swap(/<link rel="stylesheet" href="style.css" \/>/, `<link rel="stylesheet" href="style.css" />\n<link rel="stylesheet" href="web.css" />`, "the stylesheet link");
// the competition switcher (wc.js fills it) sits before the search box
swap(/<div class="search">/, `<div class="comps" id="comps"></div>\n        <div class="search">`, "the search box");
swap(/<button id="btn-expand"/, `<button id="btn-auth" class="tab auth" title="Sign in to see your record and track slips">Sign in</button>\n        <button id="btn-expand"`, "the expand button");
// wc.js defines window.wc, then loads renderer.js itself
swap(/<script src="renderer.js"><\/script>/, `<script type="module" src="wc.js"></script>`, "the renderer script tag");
writeFileSync(new URL("index.html", OUT), html);

console.log(`site/ built · ${comps.map((c) => c.short).join(" + ")} · live API ${LIVE_BASE}`);
